services:
  database:
    image: mysql:8.0.30
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_USER
      - MYSQL_DATABASE

  site:
    build: .
    environment:
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
    ports:
      - 8000:80
    volumes:
      - "./app:/code/app"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:80/healthcheck/"]
      interval: 5s
      timeout: 2s
      retries: 5

  client:
    build:
      context: .
      dockerfile: Dockerfile_client
    depends_on:
      site:
        condition: service_healthy
    environment:
      - API_URL
    volumes:
      - "./simulated_client.py:/code/simulated_client.py"
    tty: true
