services:
  database:
    image: mysql:8.0.30
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_USER
      - MYSQL_DATABASE

  site:
    build: .
    environment:
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
    ports:
      - 8000:80
    volumes:
      - "./app:/code/app"
